import matplotlib.pyplot as py
import matplotlib.patches as patch
 
#Plotting the colours of Hellas flag
i = patch.Rectangle((0,1), width=16, height=1, facecolor='blue')
h = patch.Rectangle((0,2), width=16, height=1, facecolor='white')
g = patch.Rectangle((0,3), width=16, height=1, facecolor='blue')
f = patch.Rectangle((0,4), width=16, height=1, facecolor='white')
e1 = patch.Rectangle((0,5), width=2, height=1, facecolor='blue')
e2 = patch.Rectangle((2,5), width=1, height=1, facecolor='white')
e3 = patch.Rectangle((3,5), width=13, height=1, facecolor='blue')
d1 = patch.Rectangle((0,6), width=2, height=1, facecolor='blue')
d2 = patch.Rectangle((2,6), width=1, height=1, facecolor='white')
d3 = patch.Rectangle((3,6), width=2, height=1, facecolor='blue')
d4 = patch.Rectangle((5,6), width=11, height=1, facecolor='white')
c1 = patch.Rectangle((0,5), width=5, height=1, facecolor='white')
c2 = patch.Rectangle((5,7), width=11, height=1, facecolor='blue')
b1 = patch.Rectangle((0,8), width=2, height=1, facecolor='blue')
b2 = patch.Rectangle((2,8), width=1, height=1, facecolor='white')
b3 = patch.Rectangle((3,8), width=2, height=1, facecolor='blue')
b4 = patch.Rectangle((5,8), width=11, height=1, facecolor='white')
a1 = patch.Rectangle((0,9), width=2, height=1, facecolor='blue')
a2 = patch.Rectangle((2,9), width=1, height=1, facecolor='white')
a3 = patch.Rectangle((3,9), width=13, height=1, facecolor='blue')

fig, ax = py.subplots()
ax.add_patch(a1)
ax.add_patch(a2)
ax.add_patch(a3)
ax.add_patch(b1)
ax.add_patch(b2)
ax.add_patch(b3)
ax.add_patch(b4)
ax.add_patch(c1)
ax.add_patch(c2)
ax.add_patch(d1)
ax.add_patch(d2)
ax.add_patch(d3)
ax.add_patch(d4)
ax.add_patch(e1)
ax.add_patch(e2)
ax.add_patch(e3)
ax.add_patch(f)
ax.add_patch(g)
ax.add_patch(h)
ax.add_patch(i)

py.axis('equal')
py.show()
